// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrfducdoxbzhybylufmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyZmR1Y2RveGJ6aHlieWx1Zm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MzIwODUsImV4cCI6MjA2MjQwODA4NX0.4H6nBh10z6gDj1MkBC8REyEARifYBwziNva-YJoo0ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);